//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CartableMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CartableMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.CartableMessages", typeof(CartableMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BidderInterest for Send to Accept Commission by {0} at {1} for {2}.
        /// </summary>
        public static string AddBidderInterestForSendToAcceptCommission {
            get {
                return ResourceManager.GetString("AddBidderInterestForSendToAcceptCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BidderRequest by {0} for Check Commission at {1}.
        /// </summary>
        public static string AddBidderRequestForCheckCommission {
            get {
                return ResourceManager.GetString("AddBidderRequestForCheckCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BidderRequest by {0} for Check Manger  at {1}.
        /// </summary>
        public static string AddBidderRequestForCheckManger {
            get {
                return ResourceManager.GetString("AddBidderRequestForCheckManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidderInterest Company {0} Answer at {1} for {2}.
        /// </summary>
        public static string BidderInterestCompanyAnswer {
            get {
                return ResourceManager.GetString("BidderInterestCompanyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidderInterest Invitation Company {0} Answer by {1} at {2}.
        /// </summary>
        public static string BidderInterestInvitationCompanyAnswer {
            get {
                return ResourceManager.GetString("BidderInterestInvitationCompanyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidderInterest Send to Invitation by {0} at {1}.
        /// </summary>
        public static string BidderInterestSendToInvitation {
            get {
                return ResourceManager.GetString("BidderInterestSendToInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Company {0} Request with Commercial Manager by {1} at {2}.
        /// </summary>
        public static string CompanyRequestAcceptWithCommercial {
            get {
                return ResourceManager.GetString("CompanyRequestAcceptWithCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Company {0} Request with Procurment Manager by {1} at {2}.
        /// </summary>
        public static string CompanyRequestAcceptWithManager {
            get {
                return ResourceManager.GetString("CompanyRequestAcceptWithManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Company {0} Request  with Commercial Manager  by {1} at {2}.
        /// </summary>
        public static string CompanyRequestRejectWithCommercialManager {
            get {
                return ResourceManager.GetString("CompanyRequestRejectWithCommercialManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Company {0} Request  with Procument Manager by {1} at {2}.
        /// </summary>
        public static string CompanyRequestRejectWithProcumentManager {
            get {
                return ResourceManager.GetString("CompanyRequestRejectWithProcumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Company {0} Request to Company Request with Request Review by {1} at {2}.
        /// </summary>
        public static string CompanyRequestReturnToCompanyRequest {
            get {
                return ResourceManager.GetString("CompanyRequestReturnToCompanyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Company {0} Request to Expert {3} with Commercial Manager by {1} at {2}.
        /// </summary>
        public static string CompanyRequestReturnToExpertByCommercial {
            get {
                return ResourceManager.GetString("CompanyRequestReturnToExpertByCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Company {0} Request to Expert {3} with Procument Manager by {1} at {2}.
        /// </summary>
        public static string CompanyRequestReturnToExpertByProcumentManager {
            get {
                return ResourceManager.GetString("CompanyRequestReturnToExpertByProcumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Company {0} Request to Commercial by {1} at {2}.
        /// </summary>
        public static string CompanyRequestSendToCommercial {
            get {
                return ResourceManager.GetString("CompanyRequestSendToCommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Company {0} Request to Expert by {1} at {2}.
        /// </summary>
        public static string CompanyRequestSendToExpert {
            get {
                return ResourceManager.GetString("CompanyRequestSendToExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Company {0} Request to Request Review by {1} at {2}.
        /// </summary>
        public static string CompanyRequestSendToReview {
            get {
                return ResourceManager.GetString("CompanyRequestSendToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Company {0} with {2} by {3} at {1}.
        /// </summary>
        public static string ServiceProviderCompanyRegister {
            get {
                return ResourceManager.GetString("ServiceProviderCompanyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Company {0} with {2} by {3} at {1}.
        /// </summary>
        public static string SupplierCompanyRegister {
            get {
                return ResourceManager.GetString("SupplierCompanyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BidderInterest for Send to Accept Commission by {0} at {1} for {2}.
        /// </summary>
        public static string UpdateBidderInterestForSendToAcceptCommission {
            get {
                return ResourceManager.GetString("UpdateBidderInterestForSendToAcceptCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update BidderRequest by {0} for Check Manger  at {1}.
        /// </summary>
        public static string UpdateBidderRequestForCheckManger {
            get {
                return ResourceManager.GetString("UpdateBidderRequestForCheckManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Company {0} with {2} by {3} at {1}.
        /// </summary>
        public static string VendorCompanyRegister {
            get {
                return ResourceManager.GetString("VendorCompanyRegister", resourceCulture);
            }
        }
    }
}
