//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this message.
        /// </summary>
        public static string CanNotDeleteThisMessage {
            get {
                return ResourceManager.GetString("CanNotDeleteThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی ارسال صحیح نمی باشد.
        /// </summary>
        public static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists.
        /// </summary>
        public static string CodeExists {
            get {
                return ResourceManager.GetString("CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not exists.
        /// </summary>
        public static string CodeNotExists {
            get {
                return ResourceManager.GetString("CodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Company Request Error.
        /// </summary>
        public static string CommitCompanyRequestError {
            get {
                return ResourceManager.GetString("CommitCompanyRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit company request success.
        /// </summary>
        public static string CommitCompanyRequestSucc {
            get {
                return ResourceManager.GetString("CommitCompanyRequestSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Already Exists.
        /// </summary>
        public static string CompanyAlreadyExists {
            get {
                return ResourceManager.GetString("CompanyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Confirmation/{1}.
        /// </summary>
        public static string ConfrimationEmailLink {
            get {
                return ResourceManager.GetString("ConfrimationEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email from name.
        /// </summary>
        public static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails Sent.
        /// </summary>
        public static string EmailsSent {
            get {
                return ResourceManager.GetString("EmailsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Email Template for This Project.
        /// </summary>
        public static string EmailTemplateForProjectNotFound {
            get {
                return ResourceManager.GetString("EmailTemplateForProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        public static string EmailUlreadyExists {
            get {
                return ResourceManager.GetString("EmailUlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username and password.
        /// </summary>
        public static string EnterUserNameAndPassword {
            get {
                return ResourceManager.GetString("EnterUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert data failed.
        /// </summary>
        public static string ErrorForAddData {
            get {
                return ResourceManager.GetString("ErrorForAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data failed.
        /// </summary>
        public static string ErrorForDeleteData {
            get {
                return ResourceManager.GetString("ErrorForDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data failed.
        /// </summary>
        public static string ErrorForEditData {
            get {
                return ResourceManager.GetString("ErrorForEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get data failed.
        /// </summary>
        public static string ErrorForGetData {
            get {
                return ResourceManager.GetString("ErrorForGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in send email.
        /// </summary>
        public static string ErrorInSendEmail {
            get {
                return ResourceManager.GetString("ErrorInSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire confirmation code.
        /// </summary>
        public static string ExpireConfirmationCode {
            get {
                return ResourceManager.GetString("ExpireConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Save Information.
        /// </summary>
        public static string FirstSaveInformation {
            get {
                return ResourceManager.GetString("FirstSaveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Company Registered By Commission.
        /// </summary>
        public static string HasMaterialRequisitionCompanyRegister {
            get {
                return ResourceManager.GetString("HasMaterialRequisitionCompanyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Company Registered By PurchaseOrder.
        /// </summary>
        public static string HasPurchaseOrderRegisterCompany {
            get {
                return ResourceManager.GetString("HasPurchaseOrderRegisterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sent data for insert.
        /// </summary>
        public static string HistoryDataRowIsNotAllowEmpty {
            get {
                return ResourceManager.GetString("HistoryDataRowIsNotAllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmation code.
        /// </summary>
        public static string InvalidConfirmationCode {
            get {
                return ResourceManager.GetString("InvalidConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirm password.
        /// </summary>
        public static string InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reset Token.
        /// </summary>
        public static string InvalidResetToken {
            get {
                return ResourceManager.GetString("InvalidResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tracking Code.
        /// </summary>
        public static string InvalidTrackingCode {
            get {
                return ResourceManager.GetString("InvalidTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password.
        /// </summary>
        public static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent id.
        /// </summary>
        public static string ParentIdIsNotValid {
            get {
                return ResourceManager.GetString("ParentIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters.
        /// </summary>
        public static string PasswordPolicyInvalid {
            get {
                return ResourceManager.GetString("PasswordPolicyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete form.
        /// </summary>
        public static string PleaseCompleteForm {
            get {
                return ResourceManager.GetString("PleaseCompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not send request.
        /// </summary>
        public static string RequestIsLocked {
            get {
                return ResourceManager.GetString("RequestIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset email template successful.
        /// </summary>
        public static string ResetEmailTemplate {
            get {
                return ResourceManager.GetString("ResetEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Reset-Password/{1}.
        /// </summary>
        public static string ResetPasswordFormat {
            get {
                return ResourceManager.GetString("ResetPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has children.
        /// </summary>
        public static string RoleHasChildren {
            get {
                return ResourceManager.GetString("RoleHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Exce lFile.
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email sent.
        /// </summary>
        public static string SendConfirmationEmail {
            get {
                return ResourceManager.GetString("SendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email sent.
        /// </summary>
        public static string SendConfrimationEmail {
            get {
                return ResourceManager.GetString("SendConfrimationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Email Succ!.
        /// </summary>
        public static string SendEmailSucc {
            get {
                return ResourceManager.GetString("SendEmailSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operation successful.
        /// </summary>
        public static string SuccessTheOperation {
            get {
                return ResourceManager.GetString("SuccessTheOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files have been uploaded.
        /// </summary>
        public static string TheFileshavebeenuploaded {
            get {
                return ResourceManager.GetString("TheFileshavebeenuploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Company Has Request.
        /// </summary>
        public static string ThisCompanyHasRequest {
            get {
                return ResourceManager.GetString("ThisCompanyHasRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account confimation successful.
        /// </summary>
        public static string UserAccountConfimationSuccess {
            get {
                return ResourceManager.GetString("UserAccountConfimationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Disabled.
        /// </summary>
        public static string UserAccountDisabled {
            get {
                return ResourceManager.GetString("UserAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful user authenticate.
        /// </summary>
        public static string UserAuthenticateSuccessful {
            get {
                return ResourceManager.GetString("UserAuthenticateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this section.
        /// </summary>
        public static string Youdonothaveaccesstothissection {
            get {
                return ResourceManager.GetString("Youdonothaveaccesstothissection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero record update.
        /// </summary>
        public static string ZeroRecordUpdate {
            get {
                return ResourceManager.GetString("ZeroRecordUpdate", resourceCulture);
            }
        }
    }
}
