//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesFA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesFA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.MessagesFA", typeof(MessagesFA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت درخواست عضویت شما در تاریخ {0} تایید شد.
        /// </summary>
        public static string AcceptRegisterPayment {
            get {
                return ResourceManager.GetString("AcceptRegisterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست عضویت شما در تاریخ {0} تایید شد.
        /// </summary>
        public static string AcceptRegisterRequest {
            get {
                return ResourceManager.GetString("AcceptRegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   گواهی عدم سوء پیشینه شما در تاریخ {0} انجام شد.
        /// </summary>
        public static string AcceptRequestBadBackgroundCertificate {
            get {
                return ResourceManager.GetString("AcceptRequestBadBackgroundCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما توسط رییس نظام استان در تاریخ {0} تایید شد.
        /// </summary>
        public static string AcceptRequestByProvinceMangerForLicenseRequest {
            get {
                return ResourceManager.GetString("AcceptRequestByProvinceMangerForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما توسط نماینده سازمان در تاریخ {0} تایید شد و در انتظار پرداخت صدور پروانه توسط شما می باشد.
        /// </summary>
        public static string AcceptRequestByRepresentativeOfTheOrganizationForLicenseRequest {
            get {
                return ResourceManager.GetString("AcceptRequestByRepresentativeOfTheOrganizationForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید اولیه درخواست صدور کارت المثنی در تاریخ {0} انجام شد و در انتظار پرداخت هزینه توسط شما می باشد.
        /// </summary>
        public static string AcceptRequestIssueDuplicateCard {
            get {
                return ResourceManager.GetString("AcceptRequestIssueDuplicateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید اولیه درخواست تمدید عضویت در تاریخ {0} انجام شد و در انتظار پرداخت هزینه توسط شما می باشد.
        /// </summary>
        public static string AcceptRequestMemberExtension {
            get {
                return ResourceManager.GetString("AcceptRequestMemberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید درخواست توسط {0} انجام شد.
        /// </summary>
        public static string AcceptRequestSuccessByUser {
            get {
                return ResourceManager.GetString("AcceptRequestSuccessByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید نهایی درخواست ارتقا مدرک تحصیلی در تاریخ {0} انجام شد.
        /// </summary>
        public static string AcceptUpgradeEducationRequest {
            get {
                return ResourceManager.GetString("AcceptUpgradeEducationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل خود را تایید کنید.
        /// </summary>
        public static string AcceptYourPhoneNumber {
            get {
                return ResourceManager.GetString("AcceptYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول در لیست علاقه مندی ها ذخیره شد.
        /// </summary>
        public static string AddFavoriteProduct {
            get {
                return ResourceManager.GetString("AddFavoriteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست خرید شما با موفقیت انجام شد.
        /// </summary>
        public static string AddOrderSuccess {
            get {
                return ResourceManager.GetString("AddOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید درخواست انتقال توسط استان مقصد در تاریخ {0} انجام شد.
        /// </summary>
        public static string ApprovedWithDestinationForMemberTransferRequest {
            get {
                return ResourceManager.GetString("ApprovedWithDestinationForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تایید درخواست انتقال توسط سازمان در تاریخ {0} انجام شد و  در انتظار پرداخت هزینه توسط شما می باشد.
        /// </summary>
        public static string ApprovedWithHeadquartersForMemberTransferRequest {
            get {
                return ResourceManager.GetString("ApprovedWithHeadquartersForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید درخواست انتفال توسط استان مبدا در تاریخ {0} انجام شد.
        /// </summary>
        public static string ApprovedWithSourceForMemberTransferRequest {
            get {
                return ResourceManager.GetString("ApprovedWithSourceForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف این پیام وجود ندارد.
        /// </summary>
        public static string CanNotDeleteThisMessage {
            get {
                return ResourceManager.GetString("CanNotDeleteThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف این پیام وجود ندارد.
        /// </summary>
        public static string CanNotDeleteThisMessage1 {
            get {
                return ResourceManager.GetString("CanNotDeleteThisMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی ارسال صحیح نمی باشد..
        /// </summary>
        public static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید اولیه درخواست ارتقا مدرک تحصیلی در تاریخ {0} انجام شد و در انتظار  پرداخت هزینه توسط شما می باشد.
        /// </summary>
        public static string CheckAndAcceptWithManagerUpgradeEducationRequest {
            get {
                return ResourceManager.GetString("CheckAndAcceptWithManagerUpgradeEducationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  توسط کارشناس در دست بررسی می باشد.
        /// </summary>
        public static string CheckRequestByExpertForLicenseRequest {
            get {
                return ResourceManager.GetString("CheckRequestByExpertForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما توسط  رییس نظام استان در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string CheckRequestByProvinceMangerForLicenseRequest {
            get {
                return ResourceManager.GetString("CheckRequestByProvinceMangerForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string CheckRequestForLicenseRequest {
            get {
                return ResourceManager.GetString("CheckRequestForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی درخواست توسط {0} انجام شد.
        /// </summary>
        public static string CheckRequestSuccessByUser {
            get {
                return ResourceManager.GetString("CheckRequestSuccessByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری می باشد و قبلا استفاده شده است.
        /// </summary>
        public static string CodeExists {
            get {
                return ResourceManager.GetString("CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری می باشد و قبلا استفاده شده است.
        /// </summary>
        public static string CodeExists1 {
            get {
                return ResourceManager.GetString("CodeExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده منقضی شده است.
        /// </summary>
        public static string CodeIsExpire {
            get {
                return ResourceManager.GetString("CodeIsExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string CodeNotExists {
            get {
                return ResourceManager.GetString("CodeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string CodeNotExists1 {
            get {
                return ResourceManager.GetString("CodeNotExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما برای بررسی با موفقیت ثبت شد.
        /// </summary>
        public static string CommitCompanyRequestSucc {
            get {
                return ResourceManager.GetString("CommitCompanyRequestSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما برای بررسی با موفقیت ثبت شد.
        /// </summary>
        public static string CommitCompanyRequestSucc1 {
            get {
                return ResourceManager.GetString("CommitCompanyRequestSucc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما برای بررسی با موفقیت ثبت شد.
        /// </summary>
        public static string CommitRequestSucc {
            get {
                return ResourceManager.GetString("CommitRequestSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست توسط {0} انجام شد.
        /// </summary>
        public static string CommitRequestSuccByUser {
            get {
                return ResourceManager.GetString("CommitRequestSuccByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در برقراری ارتباط.
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در برقراری ارتباط.
        /// </summary>
        public static string CommunicationError1 {
            get {
                return ResourceManager.GetString("CommunicationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری خود را تکمیل نمایید.
        /// </summary>
        public static string CompletePersonalInformation {
            get {
                return ResourceManager.GetString("CompletePersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای Active سازی حساب کاربری خود روی لینک زیر کلیک کنید \n https://localhost:3001/Confirmation/{0}.
        /// </summary>
        public static string ConfrimationEmailLink {
            get {
                return ResourceManager.GetString("ConfrimationEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای Active سازی حساب کاربری خود روی لینک زیر کلیک کنید \n https://localhost:3001/Confirmation/{0}.
        /// </summary>
        public static string ConfrimationEmailLink1 {
            get {
                return ResourceManager.GetString("ConfrimationEmailLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نظام دامپزشکی شما در تاریخ {0} صادر  شد.
        /// </summary>
        public static string CreateNezamCode {
            get {
                return ResourceManager.GetString("CreateNezamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این مشخصات قبلا ثبت نام کرده است.
        /// </summary>
        public static string CurrentUserAlreadyRegistered {
            get {
                return ResourceManager.GetString("CurrentUserAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول از لیست علاقه مندی ها حذف شد.
        /// </summary>
        public static string DeleteFavoriteProduct {
            get {
                return ResourceManager.GetString("DeleteFavoriteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد.
        /// </summary>
        public static string DeleteSuccessful {
            get {
                return ResourceManager.GetString("DeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد.
        /// </summary>
        public static string DeleteSuccessful1 {
            get {
                return ResourceManager.GetString("DeleteSuccessful1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0} تحویل داده شد.
        /// </summary>
        public static string DeliveredOrder {
            get {
                return ResourceManager.GetString("DeliveredOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک Active سازی حساب کاربری سامانه همت.
        /// </summary>
        public static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک Active سازی حساب کاربری سامانه همت.
        /// </summary>
        public static string EmailFromName1 {
            get {
                return ResourceManager.GetString("EmailFromName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل  قبلا ثبت شده است.
        /// </summary>
        public static string EmailIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده قبلا توسط کاربر دیگری استفاده شده است.
        /// </summary>
        public static string EmailUlreadyExists {
            get {
                return ResourceManager.GetString("EmailUlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده قبلا توسط کاربر دیگری استفاده شده است.
        /// </summary>
        public static string EmailUlreadyExists1 {
            get {
                return ResourceManager.GetString("EmailUlreadyExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان خارجی تکراری است.
        /// </summary>
        public static string EnNameAlreadyExists {
            get {
                return ResourceManager.GetString("EnNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و رمز عبور را وارد کنید.
        /// </summary>
        public static string EnterUserNameAndPassword {
            get {
                return ResourceManager.GetString("EnterUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و رمز عبور را وارد کنید.
        /// </summary>
        public static string EnterUserNameAndPassword1 {
            get {
                return ResourceManager.GetString("EnterUserNameAndPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطلاعات.
        /// </summary>
        public static string ErrorForAddData {
            get {
                return ResourceManager.GetString("ErrorForAddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت اطلاعات.
        /// </summary>
        public static string ErrorForAddData1 {
            get {
                return ResourceManager.GetString("ErrorForAddData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در برقراری ارتباط با درگاه پرداخت.
        /// </summary>
        public static string ErrorForCommunicationOnlinePayment {
            get {
                return ResourceManager.GetString("ErrorForCommunicationOnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف اطلاعات.
        /// </summary>
        public static string ErrorForDeleteData {
            get {
                return ResourceManager.GetString("ErrorForDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف اطلاعات.
        /// </summary>
        public static string ErrorForDeleteData1 {
            get {
                return ResourceManager.GetString("ErrorForDeleteData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ویرایش اطلاعات.
        /// </summary>
        public static string ErrorForEditData {
            get {
                return ResourceManager.GetString("ErrorForEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ویرایش اطلاعات.
        /// </summary>
        public static string ErrorForEditData1 {
            get {
                return ResourceManager.GetString("ErrorForEditData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری اطلاعات.
        /// </summary>
        public static string ErrorForGetData {
            get {
                return ResourceManager.GetString("ErrorForGetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری اطلاعات.
        /// </summary>
        public static string ErrorForGetData1 {
            get {
                return ResourceManager.GetString("ErrorForGetData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزیابی درخواست پروانه شما توسط کارشناس در تاریخ {0} ثبت و به به کارتابل دبیر استان ارسال شد.
        /// </summary>
        public static string EvalutionRequestByExpertForLicenseRequest {
            get {
                return ResourceManager.GetString("EvalutionRequestByExpertForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان استفاده از کد Active سازی پایان یافته است و کد Active سازی ارسالی نامعتبر می باشد.
        /// </summary>
        public static string ExpireConfirmationCode {
            get {
                return ResourceManager.GetString("ExpireConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان استفاده از کد Active سازی پایان یافته است و کد Active سازی ارسالی نامعتبر می باشد.
        /// </summary>
        public static string ExpireConfirmationCode1 {
            get {
                return ResourceManager.GetString("ExpireConfirmationCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تحصیلی برای این کاربر وجود ندارد.
        /// </summary>
        public static string HaveNotEducationHistories {
            get {
                return ResourceManager.GetString("HaveNotEducationHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای ذخیره ارسال نشده است.
        /// </summary>
        public static string HistoryDataRowIsNotAllowEmpty {
            get {
                return ResourceManager.GetString("HistoryDataRowIsNotAllowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای ذخیره ارسال نشده است.
        /// </summary>
        public static string HistoryDataRowIsNotAllowEmpty1 {
            get {
                return ResourceManager.GetString("HistoryDataRowIsNotAllowEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0} در حال بررسی می باشد.
        /// </summary>
        public static string InProgressOrder {
            get {
                return ResourceManager.GetString("InProgressOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد Active سازی ارسالی صحیح نمی باشد.
        /// </summary>
        public static string InvalidConfirmationCode {
            get {
                return ResourceManager.GetString("InvalidConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد Active سازی ارسالی صحیح نمی باشد.
        /// </summary>
        public static string InvalidConfirmationCode1 {
            get {
                return ResourceManager.GetString("InvalidConfirmationCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور با رمز عبور یکسان نمی باشد.
        /// </summary>
        public static string InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور با رمز عبور یکسان نمی باشد.
        /// </summary>
        public static string InvalidConfirmPassword1 {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب ایمیل نامعتبر است.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب تلفن همراه نامعتبر است.
        /// </summary>
        public static string InvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر است Token.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر است Token.
        /// </summary>
        public static string InvalidRefreshToken1 {
            get {
                return ResourceManager.GetString("InvalidRefreshToken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reset Token.
        /// </summary>
        public static string InvalidResetToken {
            get {
                return ResourceManager.GetString("InvalidResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسالی صحیح نمی باشد.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یافت نشد.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت نام کاربری نامعتبر است.
        /// </summary>
        public static string InvalidUserNameFormat {
            get {
                return ResourceManager.GetString("InvalidUserNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string InvalidUserNameOrPassword1 {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتمی با مقدار ارسالی پیدا نشد.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتمی با مقدار ارسالی پیدا نشد.
        /// </summary>
        public static string ItemNotFound1 {
            get {
                return ResourceManager.GetString("ItemNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان پرداخت وجود ندارد.
        /// </summary>
        public static string ItisNotPossibleToPay {
            get {
                return ResourceManager.GetString("ItisNotPossibleToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوپن تخفیف منقضی شده است.
        /// </summary>
        public static string KoponExpired {
            get {
                return ResourceManager.GetString("KoponExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوپن تخفیف شما اعمال شد.
        /// </summary>
        public static string KoponIsActived {
            get {
                return ResourceManager.GetString("KoponIsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوپن تخفیفی یافت نشد.
        /// </summary>
        public static string KoponNotValid {
            get {
                return ResourceManager.GetString("KoponNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  شما درخواست در حال بررسی دارید.
        /// </summary>
        public static string LockedRequestInProgressRequest {
            get {
                return ResourceManager.GetString("LockedRequestInProgressRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعاتی یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعاتی یافت نشد.
        /// </summary>
        public static string NotFound1 {
            get {
                return ResourceManager.GetString("NotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی درصورتی که درخواست پروانه شما ، در مرحله ارسال درخواست برای نماینده سازمان می باشد می توانید از ... پیگیری بفرمایید.
        /// </summary>
        public static string NotifeForForLicenseRequestDoNotAnswer {
            get {
                return ResourceManager.GetString("NotifeForForLicenseRequestDoNotAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتراض شما برای رای کمیسیون استان در تاریخ {0} برای درخواست پروانه ثبت شد .
        /// </summary>
        public static string ObjectToTheOpinionOfTheProvincialCommissionForLicenseRequest {
            get {
                return ResourceManager.GetString("ObjectToTheOpinionOfTheProvincialCommissionForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده فعلی صحیح نمی باشد.
        /// </summary>
        public static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد شده فعلی صحیح نمی باشد.
        /// </summary>
        public static string OldPasswordInvalid1 {
            get {
                return ResourceManager.GetString("OldPasswordInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت آنلاین شما با کد پیگیری {0} با خطا مواجه شده است.
        /// </summary>
        public static string OnlinePaymentError {
            get {
                return ResourceManager.GetString("OnlinePaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار انتخاب شده برای مقدار دسته بندی والد صحیح نمی باشد.
        /// </summary>
        public static string ParentIdIsNotValid {
            get {
                return ResourceManager.GetString("ParentIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار انتخاب شده برای مقدار دسته بندی والد صحیح نمی باشد.
        /// </summary>
        public static string ParentIdIsNotValid1 {
            get {
                return ResourceManager.GetString("ParentIdIsNotValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید حداقل 8 کاراکتر باشد.
        /// </summary>
        public static string PasswordPolicyInvalid {
            get {
                return ResourceManager.GetString("PasswordPolicyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید حداقل 8 کاراکتر باشد.
        /// </summary>
        public static string PasswordPolicyInvalid1 {
            get {
                return ResourceManager.GetString("PasswordPolicyInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه درخواست پروانه شما در تاریخ {0} با موفقیت انجام شد ، در انتظار بررسی درخواست توسط رییس نظام استان می باشد..
        /// </summary>
        public static string PaymentLicenseRequestSuccessAndWatingForCheckProvinceManger {
            get {
                return ResourceManager.GetString("PaymentLicenseRequestSuccessAndWatingForCheckProvinceManger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه پرداخت ارزشیابی در تاریخ {0} با موفقیت انجام شد ، شما می توانید در سامانه سایر مدارک مورد نیاز برای درخواست پروانه خود اقدام نمایید..
        /// </summary>
        public static string PaymentSuccessAndOpenFormLicenseRequest {
            get {
                return ResourceManager.GetString("PaymentSuccessAndOpenFormLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با موفقیت انجام شد.
        /// </summary>
        public static string PaymentWasSuccessful {
            get {
                return ResourceManager.GetString("PaymentWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ناموفق .
        /// </summary>
        public static string PaymentWasUnsuccessful {
            get {
                return ResourceManager.GetString("PaymentWasUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل قبلا در سامانه ثبت شده است.
        /// </summary>
        public static string PhoneNumberAlreadyExists {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تلفن همراه قبلا ثبت شده است.
        /// </summary>
        public static string PhoneNumberIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("PhoneNumberIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا داده همه کنترل های فرم را وارد کنید.
        /// </summary>
        public static string PleaseCompleteForm {
            get {
                return ResourceManager.GetString("PleaseCompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا داده همه کنترل های فرم را وارد کنید.
        /// </summary>
        public static string PleaseCompleteForm1 {
            get {
                return ResourceManager.GetString("PleaseCompleteForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  چاپ و  ارسال ارسال کارت در تاریخ {0} انجام شد ، کد مرسوله پست {1}  برای دریافت کارت می باشد.
        /// </summary>
        public static string PrintAndSendCardSuccess {
            get {
                return ResourceManager.GetString("PrintAndSendCardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  توسط دبیر استان تایید شد و در انتظار  پرداخت هزینه ارزشیابی توسط شما می باشد..
        /// </summary>
        public static string ProvinceSecretaryPrimaryAcceptForLicenseRequest {
            get {
                return ResourceManager.GetString("ProvinceSecretaryPrimaryAcceptForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  توسط دبیر استان رد شد ..
        /// </summary>
        public static string ProvinceSecretaryRejectForLicenseRequest {
            get {
                return ResourceManager.GetString("ProvinceSecretaryRejectForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  توسط کمیسیون استان تایید شد و در انتظار  پرداخت هزینه کارشناسی بازدید توسط شما می باشد..
        /// </summary>
        public static string ProvincialCommissionAcceptForLicenseRequest {
            get {
                return ResourceManager.GetString("ProvincialCommissionAcceptForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما پس از بررسی مجدد در تاریخ {0}  توسط کمیسیون استان رد شد .
        /// </summary>
        public static string ProvincialCommissionRejectForLicenseRequest {
            get {
                return ResourceManager.GetString("ProvincialCommissionRejectForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  توسط کمیسیون استان رد شد و شما می توانید تا 7 روز آینده فرصت اعتراض به رای کمیسیون استان را دارید.
        /// </summary>
        public static string ProvincialCommissionRejectForLicenseRequestWithObject {
            get {
                return ResourceManager.GetString("ProvincialCommissionRejectForLicenseRequestWithObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موفقیت انجام شد.
        /// </summary>
        public static string RegisterSuccessful {
            get {
                return ResourceManager.GetString("RegisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد مدرک تحصیلی در تاریخ {0} انچام شد.
        /// </summary>
        public static string RejectDegree {
            get {
                return ResourceManager.GetString("RejectDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0} رد شد.
        /// </summary>
        public static string RejectOrder {
            get {
                return ResourceManager.GetString("RejectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  پرداخت درخواست عضویت شما در تاریخ {0} رد شد.
        /// </summary>
        public static string RejectRegisterPayment {
            get {
                return ResourceManager.GetString("RejectRegisterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست عضویت شما در تاریخ {0} رد شد.
        /// </summary>
        public static string RejectRegisterRequest {
            get {
                return ResourceManager.GetString("RejectRegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست پروانه بعد از ارزیابی کارشناس ، توسط دبیر استان در تاریخ {0} رد شد.
        /// </summary>
        public static string RejectRequestAfterReviewRequestByProvinceSecretaryForLicenseRequest {
            get {
                return ResourceManager.GetString("RejectRequestAfterReviewRequestByProvinceSecretaryForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   رد درخواست عدم سوء پیشینه شما در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectRequestBadBackgroundCertificate {
            get {
                return ResourceManager.GetString("RejectRequestBadBackgroundCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما توسط رییس نظام استان در تاریخ {0} رد شد.
        /// </summary>
        public static string RejectRequestByProvinceMangerForLicenseRequest {
            get {
                return ResourceManager.GetString("RejectRequestByProvinceMangerForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست صدور کارت المثنی در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectRequestIssueDuplicateCard {
            get {
                return ResourceManager.GetString("RejectRequestIssueDuplicateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   رد درخواست تمدید عضویت شما در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectRequestMemberExtension {
            get {
                return ResourceManager.GetString("RejectRequestMemberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست توسط {0} انجام شد.
        /// </summary>
        public static string RejectRequestSuccessByUser {
            get {
                return ResourceManager.GetString("RejectRequestSuccessByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست ارتقا مدرک تحصیلی شما در تاریخ {0} انجام می باشد.
        /// </summary>
        public static string RejectUpgradeEducationRequest {
            get {
                return ResourceManager.GetString("RejectUpgradeEducationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست انتقال توسط استان مقصد در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectWithDestinationForMemberTransferRequest {
            get {
                return ResourceManager.GetString("RejectWithDestinationForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  رد درخواست انتقال توسط سازمان در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectWithHeadquartersForMemberTransferRequest {
            get {
                return ResourceManager.GetString("RejectWithHeadquartersForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد درخواست انتقال توسط استان مبدا در تاریخ {0} انجام شد.
        /// </summary>
        public static string RejectWithSourceForMemberTransferRequest {
            get {
                return ResourceManager.GetString("RejectWithSourceForMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست صدورالمثنی کارت شما در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string RequestReviewIssueDuplicateCardRequest {
            get {
                return ResourceManager.GetString("RequestReviewIssueDuplicateCardRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تمدید عضویت شما در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string RequestReviewMemberExtensionRequest {
            get {
                return ResourceManager.GetString("RequestReviewMemberExtensionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست انتقال شما در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string RequestReviewMemberTransferRequest {
            get {
                return ResourceManager.GetString("RequestReviewMemberTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست عضویت در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string RequestReviewRegisterRequest {
            get {
                return ResourceManager.GetString("RequestReviewRegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ارتقا مدرک تحصیلی شما در تاریخ {0} در دست بررسی می باشد.
        /// </summary>
        public static string RequestReviewUpgradeEducationRequest {
            get {
                return ResourceManager.GetString("RequestReviewUpgradeEducationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را مشخص نمائید.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را مشخص نمائید.
        /// </summary>
        public static string Required1 {
            get {
                return ResourceManager.GetString("Required1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تمپلیت ریست شد.
        /// </summary>
        public static string ResetEmailTemplate {
            get {
                return ResourceManager.GetString("ResetEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت پسورد ریست شد.
        /// </summary>
        public static string ResetPasswordFormat {
            get {
                return ResourceManager.GetString("ResetPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0} مرجوع شد.
        /// </summary>
        public static string ReturnByCustomer {
            get {
                return ResourceManager.GetString("ReturnByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست مرجوعی شما ثبت گردید.
        /// </summary>
        public static string ReturnOrderByCustomer {
            get {
                return ResourceManager.GetString("ReturnOrderByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت درخواست پروانه شما توسط دبیر استان به کارشناس برای بررسی مجدد در تاریخ {0} انجام شد.
        /// </summary>
        public static string ReturnRequestToExpertForEditForLicenseRequest {
            get {
                return ResourceManager.GetString("ReturnRequestToExpertForEditForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر دارای زیر نقش می باشد و قابل حذف نیست .
        /// </summary>
        public static string RoleHasChildren {
            get {
                return ResourceManager.GetString("RoleHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر دارای زیر نقش می باشد و قابل حذف نیست .
        /// </summary>
        public static string RoleHasChildren1 {
            get {
                return ResourceManager.GetString("RoleHasChildren1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره سازی داده ها انجام شد.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره سازی داده ها انجام شد.
        /// </summary>
        public static string SaveSuccessful1 {
            get {
                return ResourceManager.GetString("SaveSuccessful1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدی برای تایید شماره موبایل شما پیامک شد.
        /// </summary>
        public static string SendCodeConfirmPhone {
            get {
                return ResourceManager.GetString("SendCodeConfirmPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل Active سازی به آدرس ایمیل شما ارسال شد.برای Active کردن حساب کاربری باید از طریق ایمیل ارسالی اقدام نمایید.
        /// </summary>
        public static string SendConfirmationEmail {
            get {
                return ResourceManager.GetString("SendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل Active سازی به آدرس ایمیل شما ارسال شد.برای Active کردن حساب کاربری باید از طریق ایمیل ارسالی اقدام نمایید.
        /// </summary>
        public static string SendConfirmationEmail1 {
            get {
                return ResourceManager.GetString("SendConfirmationEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما ایجاد شد ، برای فعال کردن کد ارسالی را وارد نمایید.
        /// </summary>
        public static string SendConfirmationPhoneNumber {
            get {
                return ResourceManager.GetString("SendConfirmationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل Active سازی حساب کاربری.
        /// </summary>
        public static string SendConfrimationEmail {
            get {
                return ResourceManager.GetString("SendConfrimationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل Active سازی حساب کاربری.
        /// </summary>
        public static string SendConfrimationEmail1 {
            get {
                return ResourceManager.GetString("SendConfrimationEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0} آماده برای ارسال می باشد.
        /// </summary>
        public static string SendingOrder {
            get {
                return ResourceManager.GetString("SendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست پروانه شما در تاریخ {0}  برای کارشناس جهت بازدید ارسال شد..
        /// </summary>
        public static string SendRequestToExpertForLicenseRequest {
            get {
                return ResourceManager.GetString("SendRequestToExpertForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال درخواست پروانه شما برای نماینده سازمان در تاریخ {0} انجام شد.
        /// </summary>
        public static string SendRequestToRepresentativeOfTheOrganizationForLicenseRequest {
            get {
                return ResourceManager.GetString("SendRequestToRepresentativeOfTheOrganizationForLicenseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بازنشانی رمز عبور به شماره موبایل شما پیامک شد .
        /// </summary>
        public static string SendSmsForForgetPasswordSuccess {
            get {
                return ResourceManager.GetString("SendSmsForForgetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک ارسال شد.
        /// </summary>
        public static string SendSmsSuccess {
            get {
                return ResourceManager.GetString("SendSmsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید شما در تاریخ {0}  ارسال شد.
        /// </summary>
        public static string SentOrder {
            get {
                return ResourceManager.GetString("SentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید را مشخص کنید.
        /// </summary>
        public static string SpecifyTheNewPassword {
            get {
                return ResourceManager.GetString("SpecifyTheNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessTheOperation {
            get {
                return ResourceManager.GetString("SuccessTheOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string SuccessTheOperation1 {
            get {
                return ResourceManager.GetString("SuccessTheOperation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این حساب کاربری قبلا ثبت نام شده است.
        /// </summary>
        public static string ThisUserExiste {
            get {
                return ResourceManager.GetString("ThisUserExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی با موفقیت انجام شد.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی با موفقیت انجام شد.
        /// </summary>
        public static string UpdateSuccessful1 {
            get {
                return ResourceManager.GetString("UpdateSuccessful1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ها را بارگذاری کنید.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این شاخص در طراحی داشبوردها استفاده شده است.
        /// </summary>
        public static string UseIndexTemplateInDashboardDesign {
            get {
                return ResourceManager.GetString("UseIndexTemplateInDashboardDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این شاخص در طراحی داشبوردها استفاده شده است.
        /// </summary>
        public static string UseIndexTemplateInDashboardDesign1 {
            get {
                return ResourceManager.GetString("UseIndexTemplateInDashboardDesign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active سازی حساب کاربری شما انجام شد.
        /// </summary>
        public static string UserAccountConfimationSuccess {
            get {
                return ResourceManager.GetString("UserAccountConfimationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active سازی حساب کاربری شما انجام شد.
        /// </summary>
        public static string UserAccountConfimationSuccess1 {
            get {
                return ResourceManager.GetString("UserAccountConfimationSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری غیر فعال است.
        /// </summary>
        public static string UserAccountDisabled {
            get {
                return ResourceManager.GetString("UserAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت با موفقیت انجام شد.
        /// </summary>
        public static string UserAuthenticateSuccessful {
            get {
                return ResourceManager.GetString("UserAuthenticateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت با موفقیت انجام شد.
        /// </summary>
        public static string UserAuthenticateSuccessful1 {
            get {
                return ResourceManager.GetString("UserAuthenticateSuccessful1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیر فعال میباشد.
        /// </summary>
        public static string UserIsDeActive {
            get {
                return ResourceManager.GetString("UserIsDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما تا 15 دقیقه اجازه ی ورود ندارید.
        /// </summary>
        public static string YouCannotLogin {
            get {
                return ResourceManager.GetString("YouCannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترس به این قسمت ندارید.
        /// </summary>
        public static string YouDoNotHaveAccess {
            get {
                return ResourceManager.GetString("YouDoNotHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل شما تایید شد.
        /// </summary>
        public static string YourPhoneNumberIsAccept {
            get {
                return ResourceManager.GetString("YourPhoneNumberIsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییری در داده های ارسالی نسبت به قبل پیدا نشد.
        /// </summary>
        public static string ZeroRecordUpdate {
            get {
                return ResourceManager.GetString("ZeroRecordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییری در داده های ارسالی نسبت به قبل پیدا نشد.
        /// </summary>
        public static string ZeroRecordUpdate1 {
            get {
                return ResourceManager.GetString("ZeroRecordUpdate1", resourceCulture);
            }
        }
    }
}
