export const  GET_INITIAL_POSTS = "GET_INITIAL_POSTS";
export const GET_ARTICLE_SIDEBAR_INFOS = "GET_ARTICLE_SIDEBAR_INFOS";
export const CHOOSE_ARTICLE_CATEGORY = "CHOOSE_ARTICLE_CATEGORY";


//Shopping Card
export const SHOPPING_CARD_ADD_ITEM = "SHOPPING_CARD_ADD_ITEM";
export const SHOPPING_CARD_REMOVE_ITEM = "SHOPPING_CARD_REMOVE_ITEM";
export const SHOPPING_CARD_CHECKOUT = "SHOPPING_CARD_CHECKOUT";
export const SHOPPING_CARD_CLEAR = "SHOPPING_CARD_CLEAR";
export const SHOPPING_CARD_GETALL = "SHOPPING_CARD_GETALL";
export const SHOPPING_CARD_GETCount = "SHOPPING_CARD_GETCount";
export const SHOPPING_CARD_Remove_ITEMCOUNT = "SHOPPING_CARD_Remove_ITEMCOUNT";

